apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enables application status badge feature
  statusbadge.enabled: "true"

  kustomize.enabled: true
  jsonnet.enabled: false
  helm.enabled: true

  # disables admin user. Admin is enabled by default
  admin.enabled: "true"