apiVersion: v1
kind: Secret
metadata:
  name: github-helm-charts-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/CCH0124/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: github-argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/CCH0124/argocd-gitops-manifest