apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress-appset
  namespace: argo
spec:
  generators:
  - clusters: {} # all cluster
  template:
    metadata:
      name: '{{name}}-ingress-controller'
    spec:
      project: default
      sources:
      - repoURL: 'https://kubernetes.github.io/ingress-nginx'
        chart: ingress-nginx/ingress-nginx
        targetRevision: 4.4.2
        helm:
          releaseName: ingress-nginx
          version: v3
          valueFiles:
          - $values/infra/charts/nginx-ingress/values.yaml
      - repoURL: 'https://github.com/CCH0124/helm-charts.git'
        targetRevision: HEAD
        ref: values
      destination:
        server: '{{server}}'
        namespace: 'ingress-nginx'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true