apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress-appset
  namespace: argo
spec:
  generators:
  - clusters: 
      selector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - dev
              - stage
              - prd
  template:
    metadata:
      name: '{{name}}-ingress-controller'
    spec:
      project: sre-project
      sources:
      - repoURL: 'https://kubernetes.github.io/ingress-nginx'
        chart: ingress-nginx
        targetRevision: 4.10.1
        helm:
          releaseName: ingress-nginx
          version: v3
          valueFiles:
          - $values/third-party/ingress/values.yaml
      - repoURL: 'https://github.com/CCH0124/argocd-sandbox.git'
        targetRevision: HEAD
        ref: values
      destination:
        server: '{{server}}'
        namespace: 'ingress'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true