apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-app
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: sre-app
    team: sre
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.telegram: "-1002435691214"
    notifications.argoproj.io/subscribe.on-sync-status-running.telegram: "-1002435691214"
    notifications.argoproj.io/subscribe.on-sync-status-error.telegram: "-1002435691214"
    notifications.argoproj.io/subscribe.on-sync-status-unknown: "-1002435691214"
spec:
  project: sre-project
  source:
    repoURL: https://github.com/CCH0124/argocd-gitops-manifest.git
    targetRevision: v0.0.7
    path: '.'
    directory:
      recurse: true
      include: '{developer/*.yaml,devops/*.yaml,application-set/*.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: 'argo'
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:  
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      annotations:
        team: sre
        manage-by: argocd
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
