apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:dev, applications, *,  dev-project/*, allow
    p, role:dev, projects, get,  dev-project, allow
    p, role:dev, repositories, get,  *, allow
    p, role:dev, clusters, get,  *, allow
    g, devuser, role:dev
    

    p, role:pm, applications, get,  */*, allow
    p, role:pm, projects, get,  *, allow
    p, role:pm, repositories, get,  *, allow
    p, role:pm, clusters, get,  *, allow
    g, pmuser, role:pm



    p, role:op, applications, *,  */*, allow
    p, role:op, projects, *,  *, allow
    p, role:op, repositories, *,  *, allow
    p, role:op, clusters, *,  *, allow
    p, role:op, accounts, *,  *, allow
    p, role:op, certificates, *,  *, allow
    p, role:op, gpgkeys, *,  *, allow
    g, opuser, role:op
