apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: k3d-dev-cluster
    namespace: argo
  project: third-party-project
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.37.6
    helm:
      releaseName: argo-rollouts
      version: v3
      valueFiles:
      - $values/argo-rollouts/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: https://github.com/CCH0124/argocd-sandbox.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground